Update get_kern.py
Modification to line 15 due to following error:  
    version_seg = num_name.split('-')
TabError: inconsistent use of tabs and spaces in indentation
Change of print statements for python3 compatibility